spring:
  datasource:
    username: root
    url: jdbc:mariadb://localhost/login
    password: root
  jpa:
    hibernate:
      ddl-auto: update

api:
  security:
    token:
      secret: ${JWT_SECRET}

server:
  error:
    include-stacktrace: never
